POST http://localhost:3001/api/blogs/ 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbGxlIiwiaWQiOiI2MTg5MjgyZmFhYjdiZjU4NTNjZWYwODMiLCJpYXQiOjE2MzYzNzg2ODJ9.IT3EcHRHg9qwicYfZDCh3hMBHyt87Oq572Jnxva-2-Y

{ 
    "title": "ÅIFK", 
    "author": "kalle",
    "url": "https://www.apple.com",
    "likes": 1
}